(()=>{
'use strict';
const SB_URL='https://rdxaxsosqiudklhvezuq.supabase.co';
const SB_KEY='sb_publishable_abewBdHybtalh7RsfWbXUA_oOLebqMn';
const sb=window.supabase?.createClient?.(SB_URL,SB_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});if(!sb)return;
const M={user:null,workspace:null,role:null,data:{},draft:'',reply:'',review:false,listening:false,recognition:null,settings:null};
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();const dateRome=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(d||new Date());
function activeWs(){return document.querySelector('#workspaceSelect')?.value||M.workspace?.id||null}function matchSite(name){if(!name)return null;const q=norm(name);let best=null,score=0;for(const s of M.data.sites||[])for(const label of[s.name,s.client_name,s.location]){const n=norm(label);if(!n)continue;const sc=n===q?100:(n.includes(q)||q.includes(n)?80:q.split(' ').filter(w=>w.length>2&&n.includes(w)).length*18);if(sc>score){score=sc;best=s}}return score>=30?best:null}
async function init(){const {data:{session}}=await sb.auth.getSession();if(!session?.user)return;M.user=session.user;const {data:m}=await sb.from('workspace_members').select('workspace_id,role,workspaces(id,name)').eq('user_id',M.user.id);const x=(m||[]).find(v=>['owner','admin'].includes(v.role));if(!x)return;M.workspace=x.workspaces||{id:x.workspace_id};await load();patchUI()}
async function load(){const ws=activeWs();const [s,p,i]=await Promise.all([sb.from('sites').select('id,name,client_name,location').eq('workspace_id',ws),sb.from('personal_items').select('*').eq('user_id',M.user.id).neq('status','done').order('created_at',{ascending:false}).limit(60),sb.from('assistant_inbox').select('*').eq('user_id',M.user.id).order('created_at',{ascending:false}).limit(20)]);M.data={sites:s.data||[],personal:p.data||[],inbox:i.data||[]}}
function ctx(){return{today:dateRome(),sites:(M.data.sites||[]).map(x=>({id:x.id,name:x.name,client:x.client_name,location:x.location})),personal_items:(M.data.personal||[]).slice(0,25).map(x=>({id:x.id,type:x.item_type,title:x.title,due_at:x.due_at,scope:x.scope}))}}
async function ai(input){const {data:{session}}=await sb.auth.getSession();const r=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({input,mode:'capture',now:new Date().toISOString(),context:ctx()})});if(!r.ok)throw new Error('assistant');return r.json()}
async function serverAction(a){const {data:{session}}=await sb.auth.getSession();const r=await fetch('/api/execute-action',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({workspace_id:activeWs(),action:a})});const out=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(out.error||'action');e.needs_review=!!out.needs_review;throw e}return out}
async function apply(a){if(['labor_entry','material_request','income_entry','business_expense'].includes(a.type))return serverAction(a);const site=matchSite(a.site_name),ws=activeWs();if(a.type==='business_schedule'&&a.due_at){return sb.from('company_schedule').insert({workspace_id:ws,schedule_date:String(a.due_at).slice(0,10),scheduled_at:a.due_at,site_id:site?.id||null,title:a.title||'Lavoro',notes:a.details||null,status:'planned',created_by:M.user.id})}if(a.type==='memory'){return sb.from('memory_entries').insert({user_id:M.user.id,workspace_id:ws,kind:a.memory_kind||'note',subject:a.title||null,content:a.details||a.title||'',tags:[a.category,a.site_name].filter(Boolean),importance:2,event_at:a.due_at||new Date().toISOString(),metadata:{source:'matteo_os'}})}const amount=Number(a.amount||0)||null;return sb.from('personal_items').insert({user_id:M.user.id,workspace_id:ws,site_id:site?.id||null,item_type:a.type||'task',scope:a.scope==='business'?'business':'personal',title:a.title||a.details||'Voce',details:a.details||null,status:'open',priority:a.priority||'normal',due_at:a.due_at||null,remind_at:a.remind_at||null,amount,category:a.category||null,contact_name:a.contact_name||null,metadata:{site_name:a.site_name||null,paid:a.paid??null,email_to:a.email_to||null,email_subject:a.email_subject||null,email_body:a.email_body||null}})}
async function undoLast(){const {data:links}=await sb.from('assistant_action_links').select('*').eq('user_id',M.user.id).order('created_at',{ascending:false}).limit(10);for(const l of links||[]){if(l.entity_table==='personal_items')await sb.from('personal_items').update({status:'cancelled'}).eq('id',l.entity_id);else if(l.entity_table==='company_schedule')await sb.from('company_schedule').update({status:'cancelled'}).eq('id',l.entity_id);else if(l.entity_table==='material_requests')await sb.from('material_requests').update({status:'cancelled'}).eq('id',l.entity_id);else continue;return true}const last=(M.data.personal||[])[0];if(last){await sb.from('personal_items').update({status:'cancelled'}).eq('id',last.id);return true}return false}
async function organize(input){const result=await ai(input);if(result.command==='delete_last'||result.command==='replace_last')await undoLast();let review=!!result.needs_review;const created=[];for(const a of result.actions||[]){if(Number(a.confidence??1)<.6){review=true;continue}try{const r=await apply(a);if(r?.error)throw r.error;created.push(a.type)}catch(e){review=true;console.warn('matteo action',a.type,e)}}await sb.from('assistant_inbox').insert({user_id:M.user.id,workspace_id:activeWs(),source:'voice',raw_text:input,interpreted:{...result,executed:created},status:review?'needs_review':'processed'});await load();return{...result,needs_review:review,executed:created}}
function patchUI(){window.MatteoOSOperational={organize};document.addEventListener('matteo-os-organize',async e=>{try{const r=await organize(String(e.detail?.input||''));window.dispatchEvent(new CustomEvent('matteo-os-result',{detail:r}))}catch(err){console.error(err)}})}
let tries=0,t=setInterval(()=>{tries++;if(document.querySelector('#app')){clearInterval(t);init().catch(console.warn)}else if(tries>180)clearInterval(t)},500);
})();
