(()=>{
'use strict';
const SB_URL='https://rdxaxsosqiudklhvezuq.supabase.co';
const SB_KEY='sb_publishable_abewBdHybtalh7RsfWbXUA_oOLebqMn';
const sb=window.supabase?.createClient?.(SB_URL,SB_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
if(!sb)return;
const M={user:null,workspace:null,role:null,tab:'today',data:{},draft:'',reply:'',review:false,listening:false,recognition:null,settings:null};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v)||0);
const dateRome=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(d||new Date());
const dateTimeIt=s=>{if(!s)return'';try{return new Intl.DateTimeFormat('it-IT',{timeZone:'Europe/Rome',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(s))}catch{return s}};
const dateIt=s=>{if(!s)return'';try{return new Intl.DateTimeFormat('it-IT',{timeZone:'Europe/Rome',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(s.length===10?s+'T12:00:00Z':s))}catch{return s}};
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
function tomorrow(){const d=new Date();d.setDate(d.getDate()+1);return dateRome(d)}
function activeWs(){return $('#workspaceSelect')?.value||M.workspace?.id||null}
function toast(msg,bad=false){let t=$('#mos-toast');if(!t){t=document.createElement('div');t.id='mos-toast';t.style.cssText='position:fixed;z-index:80;left:50%;bottom:105px;transform:translateX(-50%);max-width:88vw;background:#0b2117;border:1px solid #236c49;color:#fff;padding:11px 14px;border-radius:14px;font:800 12px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;box-shadow:0 12px 35px #0008';document.body.appendChild(t)}t.textContent=msg;t.style.borderColor=bad?'#74313b':'#236c49';t.style.background=bad?'#271013':'#0b2117';t.style.display='block';clearTimeout(t._x);t._x=setTimeout(()=>t.style.display='none',2600)}
async function bootstrap(){try{const {data:{session}}=await sb.auth.getSession();if(!session?.user)return;M.user=session.user;const wsid=$('#workspaceSelect')?.value;const {data:members,error}=await sb.from('workspace_members').select('workspace_id,role,workspaces(id,name,slug)').eq('user_id',M.user.id);if(error)throw error;const m=(members||[]).find(x=>x.workspace_id===wsid)||(members||[]).find(x=>['owner','admin'].includes(x.role));if(!m||!['owner','admin'].includes(m.role))return;M.workspace=m.workspaces||{id:m.workspace_id,name:'Servidio OS'};M.role=m.role;await ensureSettings();mount()}catch(e){console.warn('Matteo OS bootstrap',e)}}
async function ensureSettings(){const {data}=await sb.from('assistant_settings').select('*').eq('user_id',M.user.id).maybeSingle();if(data){M.settings=data;return}const {data:c}=await sb.from('assistant_settings').insert({user_id:M.user.id,workspace_id:M.workspace?.id||null}).select('*').maybeSingle();M.settings=c||{timezone:'Europe/Rome',morning_time:'07:00',evening_time:'19:00',daily_brief_enabled:true,evening_review_enabled:true,auto_rollover:true,voice_language:'it-IT'}}
function mount(){if($('#mos-launcher'))return;const b=document.createElement('button');b.id='mos-launcher';b.innerHTML='<span class="mos-pulse"></span>🎙 Parla';b.onclick=()=>openPanel('capture');document.body.appendChild(b);const p=document.createElement('div');p.id='mos-panel';p.innerHTML='<div class="mos-head"><div class="mos-headmark">M</div><div class="mos-headtxt"><div class="mos-kicker">MATTEO OS · CERVELLO OPERATIVO</div><div class="mos-title">La tua giornata</div></div><button class="mos-close" aria-label="Chiudi">×</button></div><div class="mos-tabs"><button class="mos-tab active" data-mos-tab="today">Oggi</button><button class="mos-tab" data-mos-tab="capture">🎙 Parla</button><button class="mos-tab" data-mos-tab="tasks">Da fare</button><button class="mos-tab" data-mos-tab="memory">Memoria</button><button class="mos-tab" data-mos-tab="settings">Impostazioni</button></div><div id="mos-body" class="mos-body"></div>';document.body.appendChild(p);const mic=document.createElement('button');mic.className='mos-footer-mic';mic.id='mos-footer-mic';mic.textContent='🎙';mic.onclick=()=>{switchTab('capture');setTimeout(startVoice,80)};document.body.appendChild(mic);$('.mos-close',p).onclick=closePanel;$$('.mos-tab',p).forEach(x=>x.onclick=()=>switchTab(x.dataset.mosTab));const ob=new MutationObserver(()=>{const app=$('#app');if(app&&getComputedStyle(app).display==='none'){b.style.display='none';closePanel()}else b.style.display='flex'});ob.observe(document.body,{attributes:true,subtree:true,attributeFilter:['style','class']})}
async function openPanel(tab='today'){M.tab=tab;$('#mos-panel')?.classList.add('mos-open');document.body.style.overflow='hidden';syncTabs();await loadData();render()}
function closePanel(){stopVoice();$('#mos-panel')?.classList.remove('mos-open');document.body.style.overflow=''}
function switchTab(tab){M.tab=tab;syncTabs();render()}
function syncTabs(){$$('.mos-tab').forEach(x=>x.classList.toggle('active',x.dataset.mosTab===M.tab))}
async function loadData(){if(!M.user)return;const uid=M.user.id,ws=activeWs();const [pi,sch,ddl,mat,wt,sites,mem,inbox]=await Promise.all([sb.from('personal_items').select('*').eq('user_id',uid).neq('status','done').order('due_at',{ascending:true,nullsFirst:false}).limit(120),ws?sb.from('company_schedule').select('*').eq('workspace_id',ws).gte('schedule_date',dateRome()).lte('schedule_date',tomorrow()).order('schedule_date'):Promise.resolve({data:[]}),ws?sb.from('deadlines').select('id,title,due_date,amount_due,amount_paid,status,priority,category').eq('workspace_id',ws).in('status',['due','partial']).order('due_date').limit(20):Promise.resolve({data:[]}),ws?sb.from('material_requests').select('id,item,quantity,unit,status,priority,site_id,supplier').eq('workspace_id',ws).order('created_at',{ascending:false}).limit(30):Promise.resolve({data:[]}),ws?sb.from('worker_tasks').select('id,title,due_date,status,priority,site_id,task_type,scheduled_at').eq('workspace_id',ws).eq('assigned_to',uid).order('created_at',{ascending:false}).limit(30):Promise.resolve({data:[]}),ws?sb.from('sites').select('id,name,client_name,location,status').eq('workspace_id',ws).limit(120):Promise.resolve({data:[]}),sb.from('memory_entries').select('*').eq('user_id',uid).order('created_at',{ascending:false}).limit(100),sb.from('assistant_inbox').select('id,raw_text,status,created_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(20)]);M.data={personal:pi.data||[],schedule:sch.data||[],deadlines:ddl.data||[],materials:(mat.data||[]).filter(x=>!['resolved','delivered','done'].includes(String(x.status).toLowerCase())),workerTasks:(wt.data||[]).filter(x=>!['done','completed'].includes(String(x.status).toLowerCase())),sites:sites.data||[],memory:mem.data||[],inbox:inbox.data||[]}}
function context(){const d=M.data;return{today:dateRome(),workspace:M.workspace?.name||'Servidio OS',personal_items:(d.personal||[]).slice(0,35).map(x=>({type:x.item_type,title:x.title,due_at:x.due_at,remind_at:x.remind_at,amount:x.amount,scope:x.scope,priority:x.priority})),company_schedule:(d.schedule||[]).slice(0,20).map(x=>({date:x.schedule_date,title:x.title,notes:x.notes,status:x.status})),deadlines:(d.deadlines||[]).slice(0,15),materials:(d.materials||[]).slice(0,15).map(x=>({item:x.item,quantity:x.quantity,unit:x.unit,status:x.status,priority:x.priority})),worker_tasks:(d.workerTasks||[]).slice(0,15),sites:(d.sites||[]).slice(0,80).map(x=>({id:x.id,name:x.name,client:x.client_name,location:x.location}))}}
function render(){const b=$('#mos-body');if(!b)return;M.tab==='today'?renderToday(b):M.tab==='capture'?renderCapture(b):M.tab==='tasks'?renderTasks(b):M.tab==='memory'?renderMemory(b):renderSettings(b)}
function isToday(s){return!!s&&dateRome(new Date(s))===dateRome()}function overdue(s){return!!s&&new Date(s).getTime()<Date.now()&&!isToday(s)}
function meta(x){const a=[];if(x.due_at)a.push((overdue(x.due_at)?'⚠️ ':'')+dateTimeIt(x.due_at));if(x.amount!=null)a.push(money(x.amount));if(x.scope==='business')a.push('Lavoro');if(x.contact_name)a.push(x.contact_name);return a.join(' · ')}
function greeting(){const h=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Rome',hour:'2-digit',hour12:false}).format(new Date()));return h<12?'Buongiorno':h<18?'Buon pomeriggio':'Buonasera'}
function renderToday(b){const d=M.data,tp=(d.personal||[]).filter(x=>isToday(x.due_at)||isToday(x.remind_at)||overdue(x.due_at)),sc=(d.schedule||[]).filter(x=>x.schedule_date===dateRome()),urg=(d.deadlines||[]).filter(x=>x.due_date<=tomorrow());b.innerHTML=`<div class="mos-hero"><h2>${greeting()}, Matteo.</h2><p>${tp.length+sc.length?`Hai ${tp.length+sc.length} cose principali da gestire oggi.`:'La giornata è pulita. Puoi aggiungere tutto parlando.'}</p><div class="mos-statgrid"><div class="mos-stat"><strong>${tp.length}</strong><span>DA FARE</span></div><div class="mos-stat"><strong>${sc.length}</strong><span>LAVORI</span></div><div class="mos-stat"><strong>${urg.length}</strong><span>SCADENZE</span></div></div><div class="mos-quick"><button class="mos-chip" data-q="Che cosa devo fare oggi? Ordinami tutto per priorità.">Organizza oggi</button><button class="mos-chip" data-q="Che cosa rischio di dimenticare in base a impegni, scadenze, materiali e attività aperte?">Cosa dimentico?</button><button class="mos-chip" data-open-capture="1">＋ Dì qualcosa</button></div></div>${sectionItems(tp,'Oggi e arretrati')}${sectionSchedule(sc)}${sectionDeadlines((d.deadlines||[]).slice(0,6))}${sectionMaterials((d.materials||[]).slice(0,6))}${M.reply?`<div class="mos-section"><div class="mos-section-title">Assistente</div><div class="mos-reply">${esc(M.reply)}</div></div>`:''}`;$$('[data-q]',b).forEach(x=>x.onclick=()=>askAI(x.dataset.q));$('[data-open-capture]',b)?.addEventListener('click',()=>switchTab('capture'));bindItems(b)}
function sectionItems(items,title){return`<div class="mos-section"><div class="mos-section-title"><span>${esc(title)}</span><span class="mos-count">${items.length}</span></div><div class="mos-list">${items.length?items.map(itemHtml).join(''):'<div class="mos-empty">Niente di urgente qui.</div>'}</div></div>`}
function sectionSchedule(items){return`<div class="mos-section"><div class="mos-section-title"><span>Programma lavoro</span><span class="mos-count">${items.length}</span></div><div class="mos-list">${items.length?items.map(x=>`<div class="mos-item"><div class="mos-itemtitle">🏗️ ${esc(x.title)}</div><div class="mos-itemmeta">${esc(x.notes||'')} ${x.status?'· '+esc(x.status):''}</div></div>`).join(''):'<div class="mos-empty">Nessun cantiere programmato oggi.</div>'}</div></div>`}
function sectionDeadlines(items){return`<div class="mos-section"><div class="mos-section-title"><span>Scadenze</span><span class="mos-count">${items.length}</span></div><div class="mos-list">${items.length?items.map(x=>`<div class="mos-item"><div class="mos-itemtitle">⏰ ${esc(x.title)}</div><div class="mos-itemmeta">${dateIt(x.due_date)} · ${money(Math.max(Number(x.amount_due||0)-Number(x.amount_paid||0),0))}</div></div>`).join(''):'<div class="mos-empty">Nessuna scadenza aperta.</div>'}</div></div>`}
function sectionMaterials(items){return`<div class="mos-section"><div class="mos-section-title"><span>Materiali aperti</span><span class="mos-count">${items.length}</span></div><div class="mos-list">${items.length?items.map(x=>`<div class="mos-item"><div class="mos-itemtitle">📦 ${esc(x.item)}</div><div class="mos-itemmeta">${esc([x.quantity,x.unit,x.supplier,x.status].filter(Boolean).join(' · '))}</div></div>`).join(''):'<div class="mos-empty">Nessun materiale da gestire.</div>'}</div></div>`}
function itemHtml(x){const p=x.priority==='urgent'||x.priority==='high'?`<span class="mos-badge ${x.priority==='urgent'?'danger':'warn'}">${esc(x.priority)}</span>`:'';return`<div class="mos-item"><div class="mos-itemrow"><button class="mos-check" data-done="${esc(x.id)}">✓</button><div class="mos-itemmain"><div class="mos-itemtitle">${p}${esc(x.title)}</div><div class="mos-itemmeta">${esc(meta(x))}${x.details?'<br>'+esc(x.details):''}</div></div><button class="mos-trash" data-del="${esc(x.id)}">×</button></div></div>`}
function bindItems(r){$$('[data-done]',r).forEach(x=>x.onclick=async()=>{await sb.from('personal_items').update({status:'done',completed_at:new Date().toISOString()}).eq('id',x.dataset.done);await loadData();render();toast('Completato')});$$('[data-del]',r).forEach(x=>x.onclick=async()=>{await sb.from('personal_items').delete().eq('id',x.dataset.del);await loadData();render();toast('Eliminato')})}
function renderCapture(b){b.innerHTML=`<div class="mos-hero"><h2>Parla. Al resto penso io.</h2><p>Puoi mettere nello stesso messaggio appuntamenti, spese, cose da fare, cantieri, promemoria e idee.</p></div><div class="mos-compose"><textarea id="mos-input" placeholder="Esempio: domani alle 8 Valentina, porta ZL25. Oggi ho speso 86 euro da Ivo. Venerdì ricordami di sentire Cristian...">${esc(M.draft)}</textarea><div class="mos-actions"><button id="mos-voice" class="mos-btn secondary">🎙 Dettatura</button><button id="mos-process" class="mos-btn primary">Organizza tutto</button></div><div id="mos-status" class="mos-status"></div></div>${M.reply?`<div class="mos-reply">${esc(M.reply)}</div>`:''}${M.review?'<div class="mos-review">Una parte era ambigua: l’ho conservata nell’Inbox senza inventare i dati mancanti.</div>':''}<div class="mos-section"><div class="mos-section-title">Ultime cose dette</div><div class="mos-list">${(M.data.inbox||[]).slice(0,6).map(x=>`<div class="mos-item"><div class="mos-itemtitle">${esc(x.raw_text)}</div><div class="mos-itemmeta">${dateTimeIt(x.created_at)} · ${esc(x.status)}</div></div>`).join('')||'<div class="mos-empty">La tua Inbox è vuota.</div>'}</div></div>`;$('#mos-input').oninput=e=>M.draft=e.target.value;$('#mos-voice').onclick=startVoice;$('#mos-process').onclick=()=>processInput('capture')}
function renderTasks(b){b.innerHTML=`<div class="mos-hero"><h2>Tutto quello che hai in testa</h2><p>Attività personali e di lavoro raccolte dall’assistente, senza perdere nulla.</p></div>${sectionItems(M.data.personal||[],'Aperte')}`;bindItems(b)}
function renderMemory(b){b.innerHTML='<input id="mos-memory-search" class="mos-search" placeholder="Cerca nella memoria…"><div id="mos-memory-list" class="mos-list"></div>';const go=()=>{const q=norm($('#mos-memory-search').value),a=(M.data.memory||[]).filter(x=>!q||norm(`${x.subject} ${x.content} ${(x.tags||[]).join(' ')}`).includes(q));$('#mos-memory-list').innerHTML=a.length?a.map(x=>`<div class="mos-item mos-memory"><div class="mos-itemtitle">${esc(x.subject||x.kind||'Memoria')}</div><div class="mos-itemmeta">${esc(x.content)}<br>${dateTimeIt(x.event_at||x.created_at)}${x.tags?.length?' · '+esc(x.tags.join(', ')):''}</div></div>`).join(''):'<div class="mos-empty">Nessun ricordo trovato.</div>'};$('#mos-memory-search').oninput=go;go()}
function renderSettings(b){const s=M.settings||{};b.innerHTML=`<div class="mos-hero"><h2>Routine automatica</h2><p>Briefing del mattino e controllo serale con notifiche push.</p></div><div class="mos-settings"><div class="mos-field"><label>Briefing mattina</label><input id="mos-morning" type="time" value="${esc(String(s.morning_time||'07:00').slice(0,5))}"></div><div class="mos-field"><label>Riepilogo sera</label><input id="mos-evening" type="time" value="${esc(String(s.evening_time||'19:00').slice(0,5))}"></div><div class="mos-toggle"><span>Briefing quotidiano</span><input id="mos-daily" type="checkbox" ${s.daily_brief_enabled!==false?'checked':''}></div><div class="mos-toggle"><span>Riepilogo serale</span><input id="mos-review-toggle" type="checkbox" ${s.evening_review_enabled!==false?'checked':''}></div><button id="mos-save-settings" class="mos-btn primary">Salva impostazioni</button></div>`;$('#mos-save-settings').onclick=saveSettings}
async function saveSettings(){const p={user_id:M.user.id,workspace_id:activeWs(),morning_time:$('#mos-morning').value,evening_time:$('#mos-evening').value,daily_brief_enabled:$('#mos-daily').checked,evening_review_enabled:$('#mos-review-toggle').checked};const {data,error}=await sb.from('assistant_settings').upsert(p,{onConflict:'user_id'}).select('*').single();if(error)return toast('Errore impostazioni',true);M.settings=data;toast('Impostazioni salvate')}
function setStatus(msg,kind=''){const e=$('#mos-status');if(e){e.textContent=msg;e.className='mos-status '+kind}}
async function processInput(mode='capture',override=''){const input=String(override||M.draft||$('#mos-input')?.value||'').trim();if(!input)return toast('Dimmi o scrivi qualcosa',true);M.draft=input;M.review=false;setStatus('Sto organizzando tutto…');let result;try{result=await callAI(input,mode)}catch(e){console.warn(e);result={summary:'Nota salvata',reply:'',needs_review:true,actions:[{type:'note',scope:'personal',title:input.slice(0,100),details:input,priority:'normal',due_at:null,remind_at:null,confidence:.4}]}}try{await persist(input,result);M.reply=result.reply||result.summary||'Fatto.';M.review=!!result.needs_review;M.draft='';await loadData();render();toast(result.summary||'Salvato')}catch(e){console.error(e);setStatus('Ho conservato il testo, ma una parte non è stata registrata.','bad');toast('Controlla l’Inbox',true)}}
async function askAI(q){M.reply='Sto controllando agenda, cantieri e scadenze…';render();try{const r=await callAI(q,'ask');M.reply=r.reply||r.summary||'Nessun risultato.';render()}catch{M.reply='Non riesco a contattare l’assistente AI in questo momento. I dati salvati restano disponibili.';render()}}
async function callAI(input,mode){const {data:{session}}=await sb.auth.getSession();if(!session?.access_token)throw new Error('session');const r=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({input,mode,now:new Date().toISOString(),context:context()})});if(!r.ok)throw new Error('assistant '+r.status);return r.json()}
async function persist(raw,result){const ws=activeWs(),actions=Array.isArray(result.actions)?result.actions:[],review=!!result.needs_review||actions.some(a=>Number(a.confidence??1)<.6);const {error}=await sb.from('assistant_inbox').insert({user_id:M.user.id,workspace_id:ws,source:M.listening?'voice':'text',raw_text:raw,interpreted:result,status:review?'needs_review':'processed'});if(error)throw error;for(const a of actions){if(Number(a.confidence??1)>=.6)await applyAction(a,ws)}}
function matchSite(name){if(!name)return null;const q=norm(name);let best=null,score=0;for(const s of M.data.sites||[]){for(const label of[s.name,s.client_name,s.location]){const n=norm(label);if(!n)continue;const sc=n===q?100:(n.includes(q)||q.includes(n)?80:q.split(' ').filter(w=>n.includes(w)).length*15);if(sc>score){score=sc;best=s}}}return score>=30?best:null}
async function applyAction(a,ws){const type=String(a.type||'note'),site=matchSite(a.site_name),amount=Number.isFinite(Number(a.amount))&&Number(a.amount)!==0?Number(a.amount):null,common={user_id:M.user.id,workspace_id:ws||null,site_id:site?.id||null,item_type:type,scope:a.scope==='business'?'business':'personal',title:String(a.title||a.details||'Voce').slice(0,240),details:a.details||null,status:'open',priority:['low','normal','high','urgent'].includes(a.priority)?a.priority:'normal',due_at:a.due_at||null,remind_at:a.remind_at||null,amount,category:a.category||null,contact_name:a.contact_name||null,metadata:{site_name:a.site_name||null,email_to:a.email_to||null,email_subject:a.email_subject||null,email_body:a.email_body||null,paid:a.paid??null}};if(type==='memory'){const {error}=await sb.from('memory_entries').insert({user_id:M.user.id,workspace_id:ws||null,kind:a.memory_kind||'note',subject:a.title||null,content:a.details||a.title||'',tags:[a.category,a.site_name,a.contact_name].filter(Boolean),importance:a.priority==='urgent'?5:a.priority==='high'?4:2,event_at:a.due_at||new Date().toISOString(),metadata:{source:'matteo_os'}});if(error)throw error;return}if(type==='business_schedule'&&ws&&a.due_at){const {error}=await sb.from('company_schedule').insert({workspace_id:ws,schedule_date:String(a.due_at).slice(0,10),site_id:site?.id||null,title:common.title,notes:a.details||null,status:'planned',created_by:M.user.id});if(!error)return}if(type==='business_expense'&&ws&&amount){const {error}=await sb.from('cost_entries').insert({workspace_id:ws,site_id:site?.id||null,category:a.category||'materiali',description:a.details||a.title||'Spesa',amount,paid:a.paid!==false,due_date:a.paid===false&&a.due_at?String(a.due_at).slice(0,10):null,created_by:M.user.id,entry_date:a.paid===false?null:dateRome(),source:'manual'});if(!error){if(a.remind_at||a.paid===false)await sb.from('personal_items').insert({...common,item_type:'expense'});return}}const {error}=await sb.from('personal_items').insert(common);if(error)throw error;if(['note'].includes(type)&&String(a.details||a.title||'').length>40)await sb.from('memory_entries').insert({user_id:M.user.id,workspace_id:ws||null,kind:a.memory_kind||'note',subject:a.title||null,content:a.details||a.title||'',tags:[a.category,a.site_name].filter(Boolean),importance:2,event_at:a.due_at||null,metadata:{source:'matteo_os'}})}
function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Usa il microfono della tastiera: il testo viene organizzato allo stesso modo.',true);return}stopVoice();const r=new SR();M.recognition=r;r.lang=M.settings?.voice_language||'it-IT';r.continuous=false;r.interimResults=true;M.listening=true;$('#mos-footer-mic')?.classList.add('listening');setStatus('Ti ascolto… parla normalmente.');let final='';r.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)final+=t+' ';else interim+=t}const input=$('#mos-input');if(input){input.value=(final||interim).trim();M.draft=input.value}};r.onerror=()=>toast('Dettatura interrotta. Puoi usare il microfono della tastiera.',true);r.onend=()=>{M.listening=false;$('#mos-footer-mic')?.classList.remove('listening');if(final.trim()){M.draft=final.trim();processInput('capture',M.draft)}};try{r.start()}catch{}}
function stopVoice(){try{M.recognition?.stop()}catch{}M.recognition=null;M.listening=false;$('#mos-footer-mic')?.classList.remove('listening')}
let tries=0;const timer=setInterval(async()=>{tries++;const app=$('#app');if(app&&getComputedStyle(app).display!=='none'){clearInterval(timer);await bootstrap()}else if(tries>180)clearInterval(timer)},500);
})();
