(()=>{
'use strict';
const SB_URL='https://rdxaxsosqiudklhvezuq.supabase.co',SB_KEY='sb_publishable_abewBdHybtalh7RsfWbXUA_oOLebqMn';
const sb=window.supabase?.createClient?.(SB_URL,SB_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});if(!sb)return;
let user=null,workspace=null,sites=[],busy=false,recognition=null;
const $=s=>document.querySelector(s),norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ws(){return $('#workspaceSelect')?.value||workspace?.id}function toast(t){let x=$('#mos-toast');if(!x){x=document.createElement('div');x.id='mos-toast';x.style.cssText='position:fixed;z-index:99999;bottom:96px;left:50%;transform:translateX(-50%);background:#10251b;color:white;padding:11px 15px;border-radius:14px;font:700 13px -apple-system;box-shadow:0 8px 30px #0008';document.body.appendChild(x)}x.textContent=t;x.style.display='block';clearTimeout(x._t);x._t=setTimeout(()=>x.style.display='none',2500)}
function matchSite(name){if(!name)return null;const q=norm(name);let best=null,score=0;for(const s of sites)for(const label of[s.name,s.client_name,s.location]){const n=norm(label);if(!n)continue;const hit=q.split(' ').filter(w=>w.length>2&&n.includes(w)).length,sc=n===q?100:(n.includes(q)||q.includes(n)?80:hit*18);if(sc>score){score=sc;best=s}}return score>=30?best:null}
async function load(){const {data}=await sb.from('sites').select('id,name,client_name,location').eq('workspace_id',ws());sites=data||[]}
async function context(){const [p,sch,ddl,mat]=await Promise.all([sb.from('personal_items').select('item_type,title,due_at,remind_at,amount,scope,priority').eq('user_id',user.id).neq('status','done').limit(35),sb.from('company_schedule').select('schedule_date,title,notes,status').eq('workspace_id',ws()).order('schedule_date').limit(30),sb.from('deadlines').select('title,due_date,amount_due,amount_paid,status,priority,category').eq('workspace_id',ws()).limit(20),sb.from('material_requests').select('item,quantity,unit,status,priority,site_id,supplier').eq('workspace_id',ws()).limit(30)]);return{sites:sites.map(s=>({id:s.id,name:s.name,client:s.client_name,location:s.location})),personal_items:p.data||[],company_schedule:sch.data||[],deadlines:ddl.data||[],materials:mat.data||[]}}
async function callAI(input,mode='capture'){const {data:{session}}=await sb.auth.getSession(),r=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({input,mode,now:new Date().toISOString(),context:await context()})});if(!r.ok)throw new Error('AI non disponibile');return r.json()}
async function serverAction(a){const {data:{session}}=await sb.auth.getSession(),r=await fetch('/api/execute-action',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({workspace_id:ws(),action:a})}),o=await r.json().catch(()=>({}));if(!r.ok)throw new Error(o.error||'Registrazione non riuscita');return o}
async function apply(a){if(['labor_entry','material_request','income_entry','business_expense'].includes(a.type))return serverAction(a);const site=matchSite(a.site_name);if(a.type==='business_schedule'&&a.due_at)return sb.from('company_schedule').insert({workspace_id:ws(),schedule_date:String(a.due_at).slice(0,10),scheduled_at:a.due_at,site_id:site?.id||null,title:a.title||'Lavoro',notes:a.details||null,status:'planned',created_by:user.id});if(a.type==='memory')return sb.from('memory_entries').insert({user_id:user.id,workspace_id:ws(),kind:a.memory_kind||'note',subject:a.title||null,content:a.details||a.title||'',tags:[a.category,a.site_name].filter(Boolean),importance:2,event_at:a.due_at||new Date().toISOString(),metadata:{source:'matteo_os'}});return sb.from('personal_items').insert({user_id:user.id,workspace_id:ws(),site_id:site?.id||null,item_type:a.type||'task',scope:a.scope==='business'?'business':'personal',title:a.title||a.details||'Voce',details:a.details||null,status:'open',priority:a.priority||'normal',due_at:a.due_at||null,remind_at:a.remind_at||null,amount:Number(a.amount||0)||null,category:a.category||null,contact_name:a.contact_name||null,metadata:{site_name:a.site_name||null,paid:a.paid??null,email_to:a.email_to||null,email_subject:a.email_subject||null,email_body:a.email_body||null}})}
async function organize(input,mode='capture'){const r=await callAI(input,mode);let review=!!r.needs_review,done=[];if(mode==='capture')for(const a of r.actions||[]){if(Number(a.confidence??1)<.6){review=true;continue}try{const z=await apply(a);if(z?.error)throw z.error;done.push(a.type)}catch(e){console.warn(e);review=true}}await sb.from('assistant_inbox').insert({user_id:user.id,workspace_id:ws(),source:'voice',raw_text:input,interpreted:{...r,executed:done},status:review?'needs_review':'processed'});return{...r,needs_review:review,executed:done}}
function mount(){if($('#mos-talk'))return;const b=document.createElement('button');b.id='mos-talk';b.innerHTML='🎙';b.setAttribute('aria-label','Parla con Matteo OS');b.title='Parla con Matteo OS';b.style.cssText='position:fixed;z-index:9998;right:18px;bottom:calc(112px + env(safe-area-inset-bottom));width:58px;height:58px;border:0;border-radius:50%;padding:0;background:#20d77a;color:#04140c;font:900 26px -apple-system;box-shadow:0 10px 35px #0009;display:grid;place-items:center';b.onclick=open;document.body.appendChild(b);const p=document.createElement('div');p.id='mos-chat';p.style.cssText='display:none;position:fixed;z-index:9999;inset:0;background:#07100c;color:white;padding:env(safe-area-inset-top) 16px env(safe-area-inset-bottom);font-family:-apple-system;overflow:auto';p.innerHTML='<div style="max-width:720px;margin:auto"><div style="display:flex;justify-content:space-between;align-items:center;padding:18px 0"><div><b style="font-size:20px">Matteo OS</b><div style="font-size:12px;color:#8ca99a">Parla liberamente. Organizzo e registro io.</div></div><button id="mos-close" style="background:#17241e;color:white;border:0;border-radius:50%;width:38px;height:38px;font-size:22px">×</button></div><div id="mos-answer" style="min-height:90px;background:#0d1b14;border:1px solid #1c382a;border-radius:18px;padding:16px;line-height:1.45;margin-bottom:14px">Dimmi quello che hai in testa: lavoro, operai, spese, appuntamenti, materiali, cose da ricordare o domande.</div><textarea id="mos-input" rows="6" placeholder="Scrivi oppure premi il microfono e parla normalmente…" style="box-sizing:border-box;width:100%;background:#101a15;color:white;border:1px solid #294536;border-radius:18px;padding:15px;font:16px -apple-system;resize:none"></textarea><div style="display:flex;gap:10px;margin-top:12px"><button id="mos-mic" style="flex:1;border:0;border-radius:15px;padding:15px;background:#173326;color:white;font-weight:800">🎙 Parla</button><button id="mos-send" style="flex:1;border:0;border-radius:15px;padding:15px;background:#20d77a;color:#04140c;font-weight:900">Invia</button></div><div id="mos-state" style="padding:12px 2px;color:#9db2a7;font-size:12px"></div></div>';document.body.appendChild(p);$('#mos-close').onclick=close;$('#mos-send').onclick=send;$('#mos-mic').onclick=startVoice}
function open(){$('#mos-chat').style.display='block';document.body.style.overflow='hidden';setTimeout(()=>$('#mos-input')?.focus(),100)}function close(){try{recognition?.stop()}catch{}$('#mos-chat').style.display='none';document.body.style.overflow=''}
async function send(){if(busy)return;const i=$('#mos-input'),text=i.value.trim();if(!text)return;busy=true;$('#mos-state').textContent='Sto capendo, organizzando e registrando…';try{const r=await organize(text,'capture');$('#mos-answer').innerHTML=esc(r.reply||r.summary||'Fatto.').replace(/\n/g,'<br>')+(r.needs_review?'<br><br><b>⚠️ Una parte richiede conferma: non ho inventato i dati mancanti.</b>':'');i.value='';toast(r.summary||'Registrato')}catch(e){$('#mos-answer').textContent='Non sono riuscito a completare questa richiesta. Il testo resta qui: riprova senza perderlo.';console.error(e)}finally{busy=false;$('#mos-state').textContent=''}}
function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Su iPhone usa il microfono della tastiera nel campo testo.');$('#mos-input').focus();return}try{recognition?.stop()}catch{}recognition=new SR();recognition.lang='it-IT';recognition.continuous=false;recognition.interimResults=true;let final='';$('#mos-state').textContent='Ti ascolto… parla normalmente.';recognition.onresult=e=>{let temp='';for(let n=e.resultIndex;n<e.results.length;n++){const t=e.results[n][0].transcript;if(e.results[n].isFinal)final+=t+' ';else temp+=t}$('#mos-input').value=(final||temp).trim()};recognition.onend=()=>{$('#mos-state').textContent='';if(final.trim())send()};recognition.onerror=()=>{$('#mos-state').textContent='Usa il microfono della tastiera se la dettatura si interrompe.'};recognition.start()}
async function init(){const {data:{session}}=await sb.auth.getSession();if(!session?.user)return;user=session.user;const {data:m}=await sb.from('workspace_members').select('workspace_id,role,workspaces(id,name)').eq('user_id',user.id);const x=(m||[]).find(v=>['owner','admin'].includes(v.role));if(!x)return;workspace=x.workspaces||{id:x.workspace_id};await load();mount();window.MatteoOS={organize,open}}
let n=0,t=setInterval(()=>{n++;if($('#app')&&getComputedStyle($('#app')).display!=='none'){clearInterval(t);init().catch(console.warn)}else if(n>180)clearInterval(t)},500);
})();
