const SB_URL='https://rdxaxsosqiudklhvezuq.supabase.co';
const SB_KEY='sb_publishable_abewBdHybtalh7RsfWbXUA_oOLebqMn';
const j=(res,s,b)=>{res.status(s).setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(b))};
async function rest(path,token,opt={}){const r=await fetch(`${SB_URL}/rest/v1/${path}`,{...opt,headers:{apikey:SB_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',Prefer:'return=representation',...(opt.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(`${r.status} ${typeof data==='string'?data:JSON.stringify(data)}`);return data}
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
function matchSite(name,sites){if(!name)return null;const q=norm(name);let best=null,score=0;for(const s of sites||[])for(const label of[s.name,s.client_name,s.location]){const n=norm(label);if(!n)continue;const hits=q.split(' ').filter(w=>w.length>2&&n.includes(w)).length;const sc=n===q?100:(n.includes(q)||q.includes(n)?80:hits*18);if(sc>score){score=sc;best=s}}return score>=30?best:null}
export default async function handler(req,res){if(req.method!=='POST')return j(res,405,{error:'method'});try{const auth=String(req.headers.authorization||''),token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!token)return j(res,401,{error:'session'});const ur=await fetch(`${SB_URL}/auth/v1/user`,{headers:{apikey:SB_KEY,Authorization:`Bearer ${token}`}});if(!ur.ok)return j(res,401,{error:'session'});const user=await ur.json();const b=typeof req.body==='string'?JSON.parse(req.body):(req.body||{});let ws=String(b.workspace_id||''),a=b.action||{};if(!ws)return j(res,400,{error:'workspace'});let mem=await rest(`workspace_members?select=role&workspace_id=eq.${encodeURIComponent(ws)}&user_id=eq.${user.id}`,token);if(!mem?.some(x=>['owner','admin'].includes(x.role)))return j(res,403,{error:'forbidden'});let sites=await rest(`sites?select=id,name,client_name,location,workspace_id&workspace_id=eq.${encodeURIComponent(ws)}`,token),site=matchSite(a.site_name,sites);if(!site&&a.site_name){const visible=await rest('sites?select=id,name,client_name,location,workspace_id',token),candidate=matchSite(a.site_name,visible);if(candidate){const targetMem=await rest(`workspace_members?select=role&workspace_id=eq.${encodeURIComponent(candidate.workspace_id)}&user_id=eq.${user.id}`,token);if(targetMem?.some(x=>['owner','admin'].includes(x.role))){site=candidate;ws=candidate.workspace_id}}}const needSite=['labor_entry','income_entry','site_update'].includes(a.type);if(needSite&&!site)return j(res,422,{error:'site_required',needs_review:true});let row,table;
if(a.type==='labor_payment_update'){
  if(!a.worker_name)return j(res,422,{error:'worker_required',needs_review:true});
  const worker=encodeURIComponent(a.worker_name);
  let q=`site_labor_adjustments?select=id,site_id,worker_name,hours,amount,paid,period_label&workspace_id=eq.${encodeURIComponent(ws)}&worker_name=ilike.*${worker}*&paid=eq.false&order=created_at.asc`;
  let rows=await rest(q,token);
  if(site)rows=(rows||[]).filter(x=>x.site_id===site.id);
  if(!(rows||[]).length)return j(res,200,{ok:true,table:'site_labor_adjustments',updated:0});
  let targets=rows||[];
  if(Number(a.hours)>0){let left=Number(a.hours),picked=[];for(const x of targets){if(left<=0)break;const h=Number(x.hours||0);if(h<=left+.0001){picked.push(x);left-=h}}if(left>.0001)return j(res,422,{error:'hours_do_not_match_open_entries',needs_review:true});targets=picked}
  for(const x of targets)await rest(`site_labor_adjustments?id=eq.${x.id}`,token,{method:'PATCH',body:JSON.stringify({paid:true})});
  return j(res,200,{ok:true,table:'site_labor_adjustments',updated:targets.length,ids:targets.map(x=>x.id),site_id:site?.id||null,workspace_id:ws});
}
if(a.type==='labor_entry'){if(!a.worker_name||!a.work_date||Number(a.hours)<=0)return j(res,422,{error:'labor_fields',needs_review:true});table='site_labor_adjustments';const dup=await rest(`${table}?select=id&site_id=eq.${site.id}&worker_name=ilike.${encodeURIComponent(a.worker_name)}&period_label=eq.${encodeURIComponent(a.work_date)}&hours=eq.${Number(a.hours)}&amount=eq.${Number(a.amount||0)}`,token);if(dup?.length)return j(res,200,{ok:true,duplicate:true,table,id:dup[0].id});row={workspace_id:ws,site_id:site.id,worker_name:a.worker_name,period_label:a.work_date,hours:Number(a.hours),amount:Number(a.amount||0),paid:a.paid!==false,note:a.details||a.title||null,source:'matteo_os_voice',created_by:user.id};}
else if(a.type==='material_request'){table='material_requests';row={workspace_id:ws,site_id:site?.id||null,requested_by:user.id,item:a.title||a.details||'Materiale',quantity:a.quantity==null?null:Number(a.quantity),unit:a.unit||null,note:a.details||null,status:'requested',priority:['low','normal','high','urgent'].includes(a.priority)?a.priority:'normal'};}
else if(a.type==='income_entry'){if(!(Number(a.amount)>0))return j(res,422,{error:'amount',needs_review:true});table='cash_receipts';const d=String(a.due_at||a.work_date||new Date().toISOString()).slice(0,10);row={workspace_id:ws,site_id:site.id,amount:Number(a.amount),fiscal_year:Number(d.slice(0,4)),received_date:d,date_confirmed:true,note:a.details||a.title||'Incasso',created_by:user.id,receipt_type:a.category||'other'};}
else if(a.type==='business_expense'){if(!(Number(a.amount)>0))return j(res,422,{error:'amount',needs_review:true});table='cost_entries';const isGeneral=!site&&['general','generale','spese_generali','spese generali','overhead'].includes(norm(a.category).replace(/ /g,'_'));if(!site&&!isGeneral)return j(res,422,{error:'site_or_general_required',needs_review:true});row={workspace_id:ws,site_id:site?.id||null,category:isGeneral?'general':(a.category||'altro'),description:a.details||a.title||'Spesa',amount:Number(a.amount),paid:a.paid!==false,due_date:a.paid===false&&a.due_at?String(a.due_at).slice(0,10):null,created_by:user.id,entry_date:a.paid===false?null:String(a.due_at||new Date().toISOString()).slice(0,10),source:'matteo_os_voice'};}
else return j(res,422,{error:'unsupported_action'});
const out=await rest(table,token,{method:'POST',body:JSON.stringify(row)});return j(res,200,{ok:true,table,id:out?.[0]?.id||null,site_id:site?.id||null,workspace_id:ws});}catch(e){console.error('execute_action',e);return j(res,500,{error:'execute_failed',message:String(e?.message||e).slice(0,300)})}}
